# Generated by Django 6.0.2 on 2026-03-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_join', models.DateField()),
            ],
        ),
    ]
