# Generated by Django 6.0.1 on 2026-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Msc IT', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.CharField(default='0%', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='totalMarks',
            field=models.IntegerField(default=0),
        ),
    ]
