# Generated by Django 6.0.1 on 2026-02-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_student_course_student_percentage_student_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('studentRoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.student')),
            ],
        ),
    ]
