# Generated by Django 6.0.1 on 2026-02-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks',
        ),
        migrations.AddField(
            model_name='marks',
            name='aiml',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='cn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='dbms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marks',
            name='python',
            field=models.IntegerField(default=0),
        ),
    ]
